- src/_includes/partials/header.njk
- src/_includes/partials/nav.njk
Fixing accessibility issue I found with a quick manual assessment. Those error was not found by the accessibility automated testing recently implemented.
The `<section>` element is useless because a `<nav>` is also a section. And where the name of the section should be instead moved as a heading for the navigation element.
Also, some section lacks heading, see the three (3) HTML validation warning: https://validator.nu/?doc=https%3A%2F%2Fcds-snc.github.io%2Falpha-design-system-documentation%2Fen%2F
---
related: https://github.com/cds-snc/design-gc-conception/issues/103
> Fix accessibility issue in partials for page header

- .eleventy.js
- package.json
- src/styles/style.css
- utils/anchor.js
- utils/slugify.js
Change formatting of heading anchors to be more usable. Now only formats `h2` and `h3` headings.
**Previous format**
``` html
<h2 id="use-the-basic-button-component" tabindex="-1">
Use the basic button component 
<a class="direct-link" href="#use-the-basic-button-component">#</a>
</h2>
```
**New format** 
``` html
<h2 id="use-the-basic-button-component">
<a class="anchor-link" href="#use-the-basic-button-component">
Use the basic button component
</a>
</h2>
```
> Change heading anchor format

- .eleventy.js
- src/_includes/layouts/base.njk
- src/scripts/code-showcase.js
- src/styles/style.css
Created new shortcode for hiding/displaying code blocks and providing people with the option to copy the displayed code.
In the documentation markdown file, add the following markup to your document.
``` md
{% viewCode "lang", "id" %}
< code block code>
{% endviewCode %}
```
**lang**: Current language of page - en or fr
**id**: Unique id to represent this code block - string
> Add viewCode shortcode

- src/_data/experimentalbanner.js
- src/_includes/partials/experimentalbanner.njk
- src/_includes/partials/header.njk
- src/styles/style.css
Add an experimental banner above the header to inform users that this tool is still currently being worked on.
> feat: add experimental banner above header

- .eleventy.js
Add a name parameter to viewCode shortcode for accessibility. `View code` button will now have an `aria-label` of "View code - (name)".
``` html
{% viewCode locale id name %}
HTML code block
{% endviewCode %}
```
``` html
{% viewCode locale "primary" "primary button" %}
{% endviewCode %}
```
> Add name to viewCode shortcode

- .eleventy.js
- package.json
- src/_includes/layouts/base.njk
- src/scripts/code-showcase.js
- src/styles/style.css
Use code clipboard plugin to preserve formatting when clicking the `Copy code` button.
> Fix format when copying code from code examples

- utils/anchor.js
Based on user feedback, remove heading anchor links and switch to just using headings.
> Switch anchor links to just headings

- src/en/components/forms/input/input.md
- src/en/components/forms/textarea/textarea.md
- src/en/components/interface-elements/button/button.md
- src/fr/composants/elements-dinterface/bouton/bouton.md
- src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md
- src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md
Changing figma links to point to the community file.
Moving forward we should point all figma links at this community page instead of our master file.
> changing figma links to point at the figma community page

- .eleventy.js
- src/_includes/layouts/base.njk
- src/_includes/layouts/token-documentation.njk
- src/en/foundations/colour/base.md
- src/en/foundations/colour/tokens.md
- src/en/foundations/colour/usage.md
- src/en/foundations/spacing/base.md
- src/en/foundations/spacing/tokens.md
- src/en/foundations/spacing/usage.md
- src/en/foundations/typography/base.md
- src/en/foundations/typography/tokens.md
- src/en/foundations/typography/usage.md
- src/styles/components/_tabs.scss
- src/styles/style.css
Tabs component available. Needs a `<nav>` so we'll need to update some templates as we go to set it up within a `<nav>` container and give it a proper label. 
Additionally, this PR also sets up the tabs for the token documentation pages.
- Reworked the `token-documentation` template to loop through documentation locales, then display if a sub page exists. I think we could make this a generic partial for component documentation too. 
- Reworked base template to use nunjuck blocks, so that its easier to set data within templates. The blocks have the same default content, so this doesn't break existing pages.
> Tab navigation

- src/_includes/layouts/component-documentation.njk
- src/_includes/layouts/token-documentation.njk
- src/_includes/partials/token_table.njk
- Fix tab rendering by adding tabs collection back to component/foundation documentation layouts
- Change token_table partial to render an empty `<td>` instead of `<th>` in table heading row for preview coloumns
> Fix tab rendering + table a11y fix

- src/_data/errormessage.js
- src/_data/getcode.js
- src/_data/hint.js
- src/_includes/partials/error-message.njk
- src/_includes/partials/getcode.njk
- src/_includes/partials/hint.njk
- src/en/components/button/code.md
- src/en/components/checkbox/code.md
- src/en/components/details/code.md
- src/en/components/error-message/code.md
- src/en/components/fieldset/code.md
- src/en/components/file-uploader/code.md
- src/en/components/footer/code.md
- src/en/components/header/code.md
- src/en/components/input/code.md
- src/en/components/radio/code.md
- src/en/components/select/code.md
- src/en/components/stepper/code.md
- src/en/components/textarea/code.md
- src/fr/composants/champ-de-saisie/code.md
- src/fr/composants/zone-de-texte/code.md
Add new getcode partial for the Get your code section (English only atm).
Add hint, error-message and getcode partials to component pages.
**Note:** French version of error-message partial content will need a revision to correct always referencing checkbox
> Update content partials

- src/404.md
- src/_includes/partials/header.njk
- src/en/components/button/code.md
- src/en/components/checkbox/code.md
- src/en/components/details/code.md
- src/en/components/error-message/code.md
- src/en/components/fieldset/code.md
- src/en/components/footer/code.md
- src/en/components/header/code.md
- src/en/components/input/code.md
- src/en/components/radio/code.md
- src/en/components/stepper/code.md
- src/en/components/textarea/code.md
- src/fr/composants/champ-de-saisie/code.md
- src/fr/composants/zone-de-texte/code.md
Fix rendering and usability issues with 404 page and code pages.
- Switch iframe src to prevent scrolling on load
- Change header rendering partial to properly render header on 404 page and pages without a `translationKey`
> Fix iframe scroll + 404 page

- src/styles/_typography.scss
- src/styles/components/_tabs.scss
- src/styles/style.css
- The old tabs had some issues with accessibility so they have been redesigned
- Code has been updated to match the [changes in figma](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=3891-10337&t=ez54izbXzhGHAlWL-0)
| Before | After |
|--------|-------|
|    <img width="784" alt="Screen Shot 2023-03-08 at 16 09 36" src="https://user-images.githubusercontent.com/30609058/223850621-725c6618-2713-4daa-8e25-51582e41b482.png">  |   <img width="807" alt="Screen Shot 2023-03-08 at 16 10 16" src="https://user-images.githubusercontent.com/30609058/223850750-f9a1c5df-475a-47a5-91ec-6877dca2dd02.png">   |
- I noticed that our hover styles weren't behaving properly and jumping vertically a bit on `mouseIn` and `mouseOut` and fixed the …
> Updated tabs

- _redirects
Update redirects to forward users to newest english url if visiting old netlify url.
> Add redirect for old netlify url

- src/_data/documentation.js
- src/en/contact/contact.md
- src/en/foundations/colour/colour.md
- src/en/foundations/typography/typography.md
- src/en/pages/index.md
- src/fr/contactez/contactez.md
- src/fr/pages/index.md
Various content fixes based on [this card](https://github.com/orgs/cds-snc/projects/21/views/1?filterQuery=&pane=issue&itemId=22523176).
- Change tokens link on homepage to link to foundations overview.
- Add min-height to contact us form to allow linking to Heading anchors to display properly.
- Change "Usage" tabs to "Use case".
- Remove "tokens" from nav titles for Colour and Typography on Foundations page.
> Various content fixes based on feedback

- src/en/contact/contact.md
- src/fr/contactez/contactez.md
Up the size of email field to 50 on contact form to accommodate departmental email addresses.
> Up the size of email field to 50 on contact form

- package.json
- src/en/components/button/code.md
- src/en/components/checkbox/code.md
- src/en/components/details/code.md
- src/en/components/error-message/code.md
- src/en/components/fieldset/code.md
- src/en/components/footer/code.md
- src/en/components/header/code.md
- src/en/components/input/code.md
- src/en/components/radio/code.md
- src/en/components/stepper/code.md
- src/en/components/textarea/code.md
- src/fr/composants/Case-a-cocher/code.md
- src/fr/composants/bouton/code.md
- src/fr/composants/champ-de-saisie/code.md
- src/fr/composants/details/code.md
- src/fr/composants/en-tete/code.md
- src/fr/composants/indicateur-detape/code.md
- src/fr/composants/jeu-de-champs/code.md
- src/fr/composants/message-derreur/code.md
- src/fr/composants/pied-de-page/code.md
- src/fr/composants/radio/code.md
- src/fr/composants/zone-de-texte/code.md
Add `allow="clipboard-write"` to the iframes in the component code sections.
Resolves #134
> Fix copy button in component code sections

- src/_data/demo.js
- src/_includes/layouts/demo.njk
- src/en/foundations/colour/colour.md
- src/fr/fondements/couleur/couleur.md
- Remove unnecessary note below global focus colour tokens
- Add gcds-container example to demo pages.
> Add gcds-container example to demo

- src/_includes/partials/installation/step-2-cdn.njk
Replace unpkg links with our new CDN links for the CDN installation instructions.
> update unpkg links to use new cdn links in CDN instructions

- src/styles/_typography.scss
- src/styles/components/_component-preview-box.scss
- src/styles/style.css
Fix active and hover state errors for component preview boxes pointed out in [#161](https://github.com/cds-snc/gcds-docs/issues/161).
Closes [#161](https://github.com/cds-snc/gcds-docs/issues/161)
> Fix active and hover state for component preview boxes

- netlify.toml
Add the headers `X-Frame-Options`, `X-XSS-Protection`, `Referrer-Policy`, `X-Content-Type-Options`, and `Permissions-Policy` to design system website.
> Add security headers to site

- examples/component-name/base.md
- examples/component-name/code.md
- examples/component-name/design.md
- examples/component-name/use-case.md
- scripts/gen-component-page.js
Update the `create-component-page` script to create pages that are closer to the final documentation pages. New pages will have all shortcodes and more complex sections, like the anatomy list, already on the page. The publisher will just need to fill in the relevant information after. Pages will appear under the coming-soon section until `state` has been updated.
To use the `create-component-page` script, run `npm run create-component-page`. A prompt for `English name:` and `French name:` will appear, continue by entering the name of the component in both languages. After entering that information, English and French component pages will be created.
```
npm run create-component-page
English Name: File uploader
French name: Téléverseur de fichiers
```
This will generate the directories …
> Update create-component-page script

- src/fr/composants/contenu-pour-lecteurs-decran/case-dusage.md
- src/fr/composants/image/case-dusage.md
Image was missing tag in French
> Use consistent "Experimental" tags for components in French

- src/fr/composants/Case-a-cocher/design.md
- src/fr/composants/boite/base.md
- src/fr/composants/champ-de-saisie/base.md
- src/fr/composants/jeu-de-champs/base.md
- src/fr/composants/signature/base.md
- src/fr/composants/zone-de-texte/base.md
> Update "Other names" in French for consistency

- src/fr/composants/Case-a-cocher/case-dusage.md
French other names for checkbox in component preview didn't have the correct names, added the correct names.
> Add correct French names to other names in checkbox

- .eleventy.js
- src/en/components/checkbox/base.md
- src/en/components/error-message/base.md
- src/en/components/fieldset/base.md
- src/en/components/header/base.md
- src/en/components/input/base.md
- src/en/components/pagination/base.md
- src/en/components/radio/base.md
- src/en/components/side-navigation/base.md
- src/en/components/stepper/base.md
- src/en/components/textarea/base.md
- src/fr/composants/Case-a-cocher/base.md
- src/fr/composants/barre-de-navigation-laterale/base.md
- src/fr/composants/bouton-radio/base.md
- src/fr/composants/champ-de-saisie/base.md
- src/fr/composants/en-tete/base.md
- src/fr/composants/indicateur-detape/base.md
- src/fr/composants/jeu-de-champs/base.md
- src/fr/composants/message-derreur/base.md
- src/fr/composants/pagination/base.md
- src/fr/composants/zone-de-texte/base.md
Update component preview padding on pagination pages to not overlap on smaller screens.
Mid-size overlap change will need to happen in `gcds-pagination`
> Remove padding in pagination preview on smaller screen sizes

- src/en/components/button/base.md
- src/fr/composants/bouton/base.md
Change `type` on the `text-only` button in the Button component preview to avoid jumping to the top of the page when clicking it.
> Change text-only link to a button type

- src/en/components/components.md
- src/fr/composants/composants.md
I noticed that our current structure on the component overview page was missing an H2 heading between the `Component tags` text and the component cards. I talked to Amy and got the English + French copy from her for the new H2 heading.
This should improve the structure of the page as we now have an H2 heading to summarize/introduce the component cards.
> add h2 heading to component overview to improve structure of page

- package.json
Update to the latest versions of each `gcds` package. Features new mobile typography sizes, new components (`gcds-text` and `gcds-sr-only`) and accessibility patch for users on Chrome.
> Update GCDS packages

- src/en/components/card/use-case.md
- src/fr/composants/carte/case-dusage.md
The card preview in the use case section was missing some inline padding that I added in.
Before:
After:
> fix card preview

- src/en/components/button/use-case.md
- src/fr/composants/bouton/case-dusage.md
The button previews in the use case section were missing some inline padding that I added in.
Before:
After:
> fix button previews

- .github/workflows/docker-build-push-production.yml
- .github/workflows/docker-build.yml
Adds github workflows to build the image when changes are made to the API, as well as a build & push upon merge
> ci: add workflow for building and pushing docker images for api

- api/src/index.js
Origin doesn't come through the request on the live form, so this is a quick fix to redirect people to the correct paths on production
> fix: origin is null on live form

- api/src/index.js
- customHttp.yml
- src/en/contact/contact.md
- src/fr/contactez/contactez.md
I did a bunch of testing with attempts to get the originating host URL. This change introduces the following logic:
- Origin could be an actual host, or null, or `null` (string)
- If `origin` is invalid, try and check if headers contain `x-forwarded-host`
- If none of the options above are valid, default to using the production domains depending on language
I also found a nice way to have a custom URL for the lambda function URL ([PR here](https://github.com/cds-snc/gcds-terraform/pull/37)).
⚠️ I won't merge this PR until the reverse proxy path exists. The path will exist as soon as the [PR](https://github.com/cds-snc/gcds-terraform/pull/37) has been merged & changes have been applied by terraform.
Update: I just tested the path via curl and it works now, so this should be safe to merge.
> fix: add more checks for originating host url

- customHttp.yml
- src/en/contact/contact.md
- src/fr/contactez/contactez.md
Temporarily direct the contact us form to our sandbox URL (will switch it back once we're fully migrated)
> fix: add temp url while we still havent finished migration

- src/en/components/language-toggle/use-case.md
Remove repeated "related components" line in language toggle use case documentation.
> fix: Remove repeated line in language toggle documentation

- src/en/components/select/use-case.md
Update select's use case heading to mention the correct component.
> Fix typo in select use case documentation

- customHttp.yml
- src/en/contact/contact.md
- src/fr/contactez/contactez.md
Step x of hosting migration to AWS
This will be the final state of the contact form submission. The API endpoint that sits on a lambda will be available on `*.alpha.canada.ca/api/submission` which will then be a relative path for `*.alpha.canada.ca/api/submission`. 
---
⚠️ Do not merge until `*.cdssandbox.xyz` is released through terraform apply. Relevant PRs below:
- https://github.com/cds-snc/gcds-terraform/pull/39
- https://github.com/cds-snc/gcds-terraform/pull/40
> fix: change path to alpha

- src/fr/a-propos.md
Add 6 missing `strong` tags on French about us page to match English page
> Add missing strong tags from French about us page

- api/Dockerfile
- api/bin/entry.sh
- api/src/index.js
- api/src/package.json
The contact us form returned an Internal Server Error last January 30th when a user attempted to submit it. Upon further investigation, it seemed it was due to the environment variables not loading within the entry script. It seems to happen intermittently, or upon cold boot of the lambda. Moving the call to `getParameters` hopefully solves this issue
**Important** the parameter `gc-design-system-config` config needs to be changed from a key-value env format to a JSON format (located in api_config in the forms terraform repository)
```json
{"EMAIL_TARGET":"assistance+design@cds-snc.ca",
"NOTIFY_API_KEY":"<notify-key>",
"NOTIFY_TEMPLATE_ID":"<notify-template>"}
```
> fix: environment vars not loading, moved getParameters to lambda handler

- package.json
- src/en/components/grid/base.md
- src/en/contact/contact.md
- src/fr/contactez/contactez.md
Update to latest version of `@cdssnc/gcds-components` to receive new autocomplete updates. Add autocomplete attribute to the Full name and email fields on contact us page.
> fix: Add autocomplete to contact form fields

- src/fr/composants/champ-de-saisie/case-dusage.md
Adds FR text to the input page documentation
Changes based on [this figma file](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=12226-17251&mode=design&t=4rvDkS7Nhrzjz687-4)
Fix for
- https://github.com/cds-snc/design-gc-conception/issues/769
<kbd>
</kbd>
> docs: fr for input documentation

- src/en/components/side-navigation/base.md
- src/en/components/top-navigation/base.md
- src/fr/composants/barre-de-navigation-laterale/base.md
- src/fr/composants/barre-de-navigation-superieure/base.md
Update the top-nav and the side-nav examples to be unique.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/763)
> fix: update top-nav + side-nav examples to be unique

- .eleventy.js
- src/en/components/grid/base.md
- src/en/components/grid/code.md
- src/fr/composants/grille/code.md
- src/scripts/code-showcase.js
- src/styles/components/_code-showcase.scss
- src/styles/style.css
Fix `view code` and `copy code` buttons on the grid code page.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/762)
> fix: view and copy code buttons on grid code page

- src/en/components/grid/code.md
- src/fr/composants/grille/code.md
When using the `gcds-grid` component, the `tag` property can accept different values. This can cause issues if a developer uses an element incorrectly. Adding new guidance about the tag use to the grid code guidance.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/757)
> feat: add new guidance for grid component

- src/_data/tabsnav.js
- src/_includes/layouts/component-documentation.njk
- src/en/components/breadcrumbs/base.md
- src/fr/composants/Chemin-de-navigation/base.md
When viewing the page landmarks, several landmarks are labeled as "Breadcrumbs navigation". This includes:
- The breadcrumbs in the header slot
- The breadcrumbs component example
- The tabs (Use case, design, code)
- The breadcrumb example in the code builder
Note: We will not be able to remove the breadcrumbs landmark from the code builder. The only way to remove it would be to change the component itself which doesn't make sense OR to hide the code builder for the breadcrumbs completely for screen reader users which is also not a great option.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/761)
> fix: breadcrumbs navigation landmark being repeated

- src/_data/nav.js
- src/en/components/side-navigation/base.md
- src/en/components/theme-and-topic-menu/base.md
- src/en/components/top-navigation/base.md
- src/fr/composants/barre-de-navigation-laterale/base.md
- src/fr/composants/barre-de-navigation-superieure/base.md
- src/fr/composants/menu-des-themes-et-sujets/base.md
Updated top-nav label for main page navigation. Added `aria-hidden` to other menu components (`side-nav`, `top-nav`, `topic-menu`) to avoid confusing navigation landmarks for assistive technology users.
> Update top nav label

- src/_data/footer.js
- src/_includes/layouts/base.njk
- src/_includes/layouts/home.njk
- src/en/about-us.md
- src/en/en.json
- src/en/privacy-notice.md
- src/fr/avis-de-confidentialite.md
- src/fr/fr.json
Create a privacy notice page for the GCDS website and use this opportunity to include the main band of the footer to be more aligned with Canada.ca guidance (Sam's recommendation for this is in the Zenhub ticket).
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/786)
[English content](https://docs.google.com/document/d/1dMlZNWSvmip-46DWnn58BrTpk1hiYOFC2RtJ0-eZ0LU/edit#heading=h.ol1g61vav7xc)
[French content](https://docs.google.com/document/d/152Z_H683zjFaLg1D7bbUsfr49fY_g1Z_BCr9Lmrzev0/edit)
> feat: add new privacy notice page

- src/en/components/button/use-case.md
- Removed last bullet point in use case guidance. It was related to the skip-to-content button which is now under role.
> chore: update use-case.md for Button

- src/fr/composants/bouton/cas-dutilisation.md
Removed last bullet point in use case guidance. It was related to the skip-to-content button which is now under role.
- Replaces #320
> chore: update bouton cas-dutilisation.md

- README.md
> docs: fixes typo in `README.md`

- src/fr/composants/masquage-accessible/code.md
Just noticed the code preview iframe language was still set to `en` instead of `fr`.
> fix: Screenreader-only French code preview language

- package.json
- src/en/styles/colour/colour.md
- src/fr/styles/couleur/couleur.md
Add new global background tokens to our documentation site to help inform users about our main brand colour.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/731)
Note: currently waiting on translation.
> feat: add global background tokens (en)

- src/en/components/error-summary/design.md
- src/en/components/error-summary/use-case.md
- src/fr/composants/resume-de-erreurs/cas-dutilisation.md
- src/fr/composants/resume-de-erreurs/design.md
Improve error summary alt text - even though we reverted the error summary style changes, Amy had worked on improving the alt text descriptions for the error summary preview + anatomy images which I still want to update.
> refactor: improve error summary alt text

- src/_data/installation.js
- src/_includes/partials/installation/step-2-vue.njk
Update Vue installation to use instructions from the Vue readme.
Will merge once`@cdssnc/gcds-components-vue` package goes live.
> feat: Update Vue installation instructions to use new Vue package

- .eleventy.js
- src/_data/installation.js
- src/_includes/partials/installation/step-2-angular.njk
- src/_includes/partials/installation/step-2-cdn.njk
- src/_includes/partials/installation/step-2-node.njk
- src/_includes/partials/installation/step-2-react.njk
- utils/cdn-info.js
Update CDN installation instructions on the website. As a user, I want to use a specific version of the gcds packages so that my application does not get any breaking changes.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/753)
> docs: update CDN installation instructions

- .eleventy.js
- api/src/constants.js
- api/src/freshdesk.js
- api/src/index.js
- api/src/notify.js
- api/src/utils.js
- package.json
- src/_data/contactus.js
- src/en/contact/contact.md
- src/fr/contactez/contactez.md
- Refactored the old API and added a freshdesk integration
- Added an encode filter for eleventy so we don't always have to write the html encoding (had to do so with the radio group on the contact us form)
- Followed the guide from here: https://github.com/cds-snc/platform-helpdesk/wiki/GC-Design-System-How-to-create-Freshdesk-tickets-using-the-API
- Add tags as appropriate. Fixed the `learnMore` checkbox to better handle the logic for this. We need to set the `name` on those checkboxes to be different, I noticed that `value` is not enough especially when testing I would just get `learnMore: checked` and not the actual value
- Use the appropriate language for the different fields
-  I've kept most of the other settings the same
``` 
const postData = JSON.stringify({
name: name ? name : …
```
> feat: contact us form freshdesk integration

- src/en/components/grid/code.md
- src/fr/composants/grille/code.md
Change formatting of `gcds-grid` examples to prevent an extra `</p>` tag from appearing behind the `gcds-grid` tag in the code highlight on the code pages. 
``` html
<gcds-grid tag="article" columns="repeat(auto-fit, minmax(100px, 300px))" gap="500"></p>
<p>This is some example content to display the grid component.</p>
<p>This is some example content to display the grid component.</p>
<p>This is some example content to display the grid component.</p>
</gcds-grid>
```
``` html
<gcds-grid tag="article" columns="repeat(auto-fit, minmax(100px, 300px))" gap="500">
<p>This is some example content to display the grid component.</p>
<p>This is some example content to display the grid component.</p>
<p>This is some example content to display the grid component.</p>
</gcds-grid>
```
> fix: Remove end paragraph tag from gird example

- customHttp.yml
- src/_includes/layouts/base.njk
- src/_includes/layouts/home.njk
There's an error loading fontawesome; I copied our installation instructions and used that instead for consistency and to get rid of the error.
> fix: error loading old fontawesome kit

- src/en/components/button/design.md
Removed a paragraph that did not exist in FR and had a missing word.
See issue https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/953
- https://github.com/cds-snc/design-gc-conception/issues/953
On the Button-design page, this paragraph is not found in FR, moreover there seems to be a missing word after "other" that is needed. Removing the paragraph for now: 
"Tip: Language constructions like sign up and sign in can be confusing because the "up" and "in" add little meaning and alongside other they can be hard to tell apart."
The EN will be removed until later time when the missing word is added and the FR is included
> Removed a paragraph that did not exist in FR and had a missing word.

- src/en/styles/typography/typography.md
Deleted extra "and" in "Typography and accessibility" heading
There were two "and"s in the heading "Typography and and accessibility"
---
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> Update typography - and and.md

- src/en/components/radio/base.md
- src/en/components/radio/code.md
- src/en/components/radio/design.md
- src/en/components/radio/use-case.md
- src/fr/composants/bouton-radio/base.md
- src/fr/composants/bouton-radio/cas-dutilisation.md
- src/fr/composants/bouton-radio/code.md
- src/fr/composants/bouton-radio/design.md
Fixes
- https://github.com/cds-snc/design-gc-conception/issues/982
1. Search for "sentence case" (EN link: https://pr-373.djtlis5vpn8jd.amplifyapp.com/en/search/?q=sentence+case)
2. Should not list the deprecated Radio component in the results
> fix(search): hide deprecated components from search

- api/src/freshdesk.js
- api/src/index.js
- api/src/notify.js
While testing the updated NodeJS image, I realized that it was still saying "successfully sent to freshdesk" although it had failed. This PR moves that line to the part of the code where it actually sends to freshdesk successfully.
> chore: update error logging

- README.md
README has the English domain listed
> docs: fix link to FR site

- src/en/components/pagination/code.md
- src/fr/composants/pagination/code.md
Remove mention of `pageChangeHandler` from pagination Code guidance. This function has been replaced with custom events and details in `v0.21.0` of `@cdssnc/gcds-components`
> fix: Remove mention of pageChangeHandler

- package.json
Update doc site to use latest versions of `gcds-tokens` and `gcds-components` to take advantage of a11y fixes made for Safari.
> chore: Update GC Design System packages (tokens + components)

- src/en/en.json
- src/en/roadmap.md
- src/fr/feuille-de-route.md
- src/fr/fr.json
> feat: add new roadmap page

- src/en/components/grid/base.md
- src/en/components/grid/code.md
- src/en/components/grid/design.md
- src/fr/composants/grille/base.md
- src/fr/composants/grille/code.md
- src/fr/composants/grille/design.md
- src/images/en/components/anatomy/gcds-grid-anatomy.svg
- src/images/fr/components/anatomy/gcds-grid-anatomy.svg
A user pointed out that we still had guidance on the documentation site for the `gcds-grid` `gap` property which was removed a while ago and was replaced with a consistent gap value for all grids.
Updating the guidance with this PR to remove the old guidance and update the grid examples on the code tab.
> fix: update grid guidance

- src/images/common/components/preview-details.svg
Noticed during our call with the OAS team today that the preview image for the details component was still showing the old border alignment. I updated the image in Figma and here to match the new design.
> fix: update details preview image to align border

- src/en/contact/contact.md
- src/en/get-involved.md
- src/en/styles/styles.md
- src/fr/contactez/contactez.md
- src/fr/simpliquer.md
- src/fr/styles/styles.md
Remove "Styles" from our top-nav and replace with a link to the "Get involved" page instead.
> refactor: replace "styles" with "get involved" in top-nav

- src/en/accessibility.md
- src/en/roadmap.md
- src/fr/accessibilite.md
- src/fr/feuille-de-route.md
Adding a new accessibility page.
Changes to the Roadmap pages in EN and FR: fixes, styling changes, adding status for each item.
> feat: add new accessibility page

- src/en/components/grid/design.md
Fix typo in `gcds-grid` design guidance using wrong "your".
> fix: Typo within grid design guidance.

- package.json
Updates 11ty to `2.0.1` (major upgrade)
This update fixes all current security warnings on package dependencies
> deps: upgrade 11ty to 2.0.1

- src/fr/simpliquer.md
Update to the Get Involved (French) page.  
No changes to "Contribute to next priorities" section.
Changes to Coming Soon (à venir) section:
Change to subtitle from "Composants à venir" to "Composants et modèles à venir"
Remove Card, Stepper and Date Input
Add Avis (notice), Modèle de page de sujet (Topic Page Template), Modèle de page ministérielle (Ministerial Page Template), Modèle d’application de départ VueJS (VueJS Starter App Template).
---
> Sequential steps (1., 2., 3., ...) that describe how to test this …
> Update S'impliquer FR.md

- src/en/get-involved.md
Update to the Get Involved (English) page.  
No changes to "Contribute to next priorities" section.
Changes to Coming Soon section:
Change to subtitle from "Upcoming components" to "Upcoming components and templates.
Remove Card, Stepper and Date Input
Add Notice, Topic Page Template, Ministerial Page Template, VueJS Starter App Template.
---
> include any …
> Update get-involved ENG.md

- src/_data/componenttags.js
- src/_includes/layouts/component-overview.njk
- src/_includes/partials/components-tags.njk
- src/en/components/breadcrumbs/use-case.md
- src/en/components/components.md
- src/en/components/date-modified/use-case.md
- src/en/components/footer/use-case.md
- src/en/components/header/use-case.md
- src/en/components/language-toggle/use-case.md
- src/en/components/search/use-case.md
- src/en/components/signature/use-case.md
- src/fr/composants/Chemin-de-navigation/cas-dutilisation.md
- src/fr/composants/bascule-de-langue/cas-dutilisation.md
- src/fr/composants/composants.md
- src/fr/composants/date-de-modification/cas-dutilisation.md
- src/fr/composants/en-tete/cas-dutilisation.md
- src/fr/composants/pied-de-page/cas-dutilisation.md
- src/fr/composants/recherche/cas-dutilisation.md
- src/fr/composants/signature/cas-dutilisation.md
This PR is for changes identified in
- https://github.com/cds-snc/design-gc-conception/issues/1000
Tasks:
- French components overview page: https://pr-429.d35vdwuoev573o.amplifyapp.com/fr/composants/
- English components overview page: https://pr-429.djtlis5vpn8jd.amplifyapp.com/en/components/
> Doc updates: Provide a faster way to github

- customHttp.yml
The preview for the basic page templates aren't showing up, even if they're a subdomain. We need to add it explicitly.
[Basic Page Templates Preview FRENCH](https://pr-448.d35vdwuoev573o.amplifyapp.com/fr/modeles-de-page/basic/apercu/)
[Basic Page Templates Preview ENGLISH](https://pr-448.djtlis5vpn8jd.amplifyapp.com/en/page-templates/basic/preview/)
> chore: add our cdn domain to the csp

- .github/workflows/build-eleventy.yaml
Updated the workflow to use the GITHUB_TOKEN and updated the peaceiris/actions-gh-pages github action to use the latest version.
> Updating github token and version of workflow for evently build workflow

- .eleventy.js
- src/_data/registerdemos.js
- src/en/en.json
- src/en/register-for-a-demo.md
- src/fr/fr.json
- src/fr/inscrivez-vous-a-une-demonstration.md
Add register for demo page (/en/register-for-a-demo/) to allow visitors to our site to see upcoming demos and register to attend the demos.
The demos are generated using the `/src/_data/registerdemos.js` data file.
```js
{
date: "2025-01-21", // YYYY-MM-DD format
starttime: "13:00",   // 24h hour format
endtime: "14:00",    // 24h hour format
lang: 'en',         // en or fr
link: 'https://examplelink.link/' 
},
```
[English page](https://pr-455.djtlis5vpn8jd.amplifyapp.com/en/register-for-a-demo)
[French page](https://pr-455.d35vdwuoev573o.amplifyapp.com/fr/inscrivez-vous-a-une-demonstration/)
> feat: Add register for demo page

- src/en/roadmap.md
- Updated status of roadmap items post Q2 2025.
- Edited Templates line item, reduced scope to only basic page template. 
- Separated Tag component and marked as deprioritized. Added a disclaimer on changes to be expected to the roadmap.
English roadmap updates, mostly status and some slight refinement. Added disclaimer at the end.
---
> include any …
> docs: update roadmap.md

- src/_data/nav.js
The 's' in GC Design System in the main navigation should be 'S'
> fix: typo in main navigation

- README.md
Adding a small addition to our installation instructions. After incorporating the templates into the documentation site, it is necessary to run `npm run build` before running `npm start` for the first time to ensure the application functions correctly.
Updated the installation steps to include the `npm run build` command before `npm start`.
I'm still waiting for the French translation. I will update this PR once I hear back from the translation team.
> chore: add additional instructions to readme

- src/en/styles/typography/typography.md
- src/fr/styles/typographie/typographie.md
When checking something on our typography page, I noticed that the font weights table was positioned below the "Italics" content section instead of the "Font weights" content section. I moved the table in EN and FR to be placed right below the "Font weight" content.
Before:
After:
> docs: fix font weight table position on typography page

- src/_data/footer.js
Change contextual footer heading from "Canadian Digital Service" to "GC Design System" and "Service numérique canadien" to "Système de design GC"
The links direct to GC Design System pages; it was previously misleading with CDS as the Heading.  
For reference on appropriateness, "Digital Transformation Office" posts their team name in their contextual footer heading.
Ref to Github issue #1361
---
> and/or any …
> Update footer.js - Change Contextual footer heading

- src/en/components/grid/code.md
- src/fr/composants/grille/code.md
Adding guidance for the grid gap property back to the code tab on the grid page.
[EN guidance](https://pr-474.djtlis5vpn8jd.amplifyapp.com/en/components/grid/code#add-spacing-between-columns) for grid gap.
[FR guidance](https://pr-474.d35vdwuoev573o.amplifyapp.com/fr/composants/grille/code#ajoutez-un-espacement-entre-les-colonnes) for grid gap.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1321) for this change.
> docs: add guidance for grid gap prop

- customHttp.yml
Currently the component preview iframes are being blocked by the Content Security Policy. Adding the site's domains to the list to allow iframe.
See https://design-system.alpha.canada.ca/en/components/grid/code/ for error
> fix: Component preview iframe permissions

- customHttp.yml
One more step to fix component preview issue.
> fix: update x-frame-options to allow component previews

- src/en/components/fieldset/design.md
- src/fr/composants/jeu-de-champs/design.md
the words "legend" and "hint" were bolded. Removed that formatting.
> Fix: remove bold from fieldset's design section

- src/en/contact/contact.md
- src/fr/contactez/contactez.md
> Update to EN and FR pages 
> Adding notice for GitHub support form 
> Removing sign up for demo checklist option from form and adding content for demo registration page ahead of contact flow
> Updating contact form description/intro to reflect actual/latest iteration of form content 
> Adding specific content about the intended audience and use of the form
> Adding link for a way out for people who need GC services 
> Hint text to remind not to submit personal (Protected) info
> Feat: Update contact.md

- src/en/contact/contact.md
- src/fr/contactez/contactez.md
This change removes the `size` prop from both the `name` and `email` fields in the contact us form.
- The size prop on the email field was previously set to a value larger than the default maximum field width, causing it to be overwritten and inconsistent with the rest of the form’s design.
- The size prop on the name field was removed to prevent unnecessary limitations on field width, as some names may exceed the default maximum width.
This ensures that both fields maintain a consistent, flexible width for better user experience.
> fix: remove size prop from contact us name and input field

- src/en/components/grid/code.md
- src/fr/composants/grille/code.md
Remove extra `</p>` tag that appears in code examples of the grid component on code pages ([EN](https://design-system.alpha.canada.ca/en/components/grid/code/)/[FR](https://systeme-design.alpha.canada.ca/fr/composants/grille/code/)).
> fix: Remove extra closing p tag from grid code example

- .eleventy.js
- src/en/components/breadcrumbs/base.md
- src/en/components/breadcrumbs/code.md
- src/en/components/footer/base.md
- src/en/components/footer/code.md
- src/en/components/header/base.md
- src/en/components/header/code.md
- src/en/components/theme-and-topic-menu/base.md
- src/en/components/theme-and-topic-menu/code.md
- src/fr/composants/chemin-de-navigation/base.md
- src/fr/composants/chemin-de-navigation/code.md
- src/fr/composants/en-tete/base.md
- src/fr/composants/en-tete/code.md
- src/fr/composants/menu-thematique/base.md
- src/fr/composants/menu-thematique/code.md
- src/fr/composants/pied-de-page/base.md
- src/fr/composants/pied-de-page/code.md
- src/scripts/component-preview-iframe.js
https://github.com/cds-snc/gcds-components/issues/771
To prevent the code/component preview iframes from navigating to new pages and becoming grey screens, add a new `externalLinks` query string to allow the browser to follow the clicked links.
1. On https://design-system.alpha.canada.ca/en/components/footer/code/ navigate to the code editor displaying the `gcds-footer. 
2. Click one of the links in the main or sub band.
3. Notice the iframe turns into a grey box.
4. On this branch locally or on the preview environment.
5. Navigate to the code page of footer.
6. Click one of the links in the main or sub band.
7. The browser should now navigate to the clicked link's `href`
1. On a local copy of `main` brain, navigate to http://localhost:8080/en/components/breadcrumbs/.
2. Click the …
> fix: grey screen when clicking external links in iframes

- src/styles/style.scss
Sass is deprecating the `@import` rule. This is part of a broader move towards using the `@use` and `@forward` rules, which are more powerful and maintainable in the long run.
Replacing `@import` with `@use` to align with the new standards.
> chore: fix sass import warning

- src/scripts/component-preview.js
The current implementation of the component-preview.js script triggers a `TypeError (Cannot read properties of null (reading 'height'))` when a page does not contain an iframe with the ID `component-preview`. This occurs because the script attempts to access the height property of a non-existent iframe.
This update adds a check to ensure the iframe element is present before attempting to read or modify its properties, preventing the error when the iframe is missing from the page.
> chore: fix TypeError from component preview

- cypress/e2e/a11y-en.cy.js
- cypress/e2e/a11y-fr.cy.js
Closes https://github.com/cds-snc/gcds-docs/issues/528
Update accessibility tests to wait until the `gcds-header` has hydrated. This will hopefully stop the basic page preview pages from randomly failing when tests are run on GitHub workflows. My theory as to why it was failing is the component JS files are being loaded in by CDN causing slower hydration of all components so when the accessibility tests run, not all components are fully rendered.
> fix: Random accessibility test failures

- scripts/templates.js
To add the current version being used in `gcds-components` and `gcds-utility` to the basic page template code, move the `codeContent` logic below the version replacement logic in the `templates.js` script.
https://github.com/cds-snc/design-gc-conception/issues/1387
1. On `main` branch, run `npm run build` & `npm run start`.
2. Visit http://localhost:8080/en/page-templates/basic/code/.
3. Notice the version numbers for the components and UF imports are formatted as `<version-number>`.
4. On this branch, run `npm run build` & `npm run start`.
5. Visit http://localhost:8080/en/page-templates/basic/code/.
6. Notice the version numbers the components and UF imports now match the version numbers in use by the 11ty docs site.
> feat: Add version numbers in page templates code page

- src/en/page-templates/basic/code.md
- src/fr/modeles-de-page/basic/code.md
- src/scripts/code-copy.js
Based on feedback, place the copy button for template code examples at the top of the template page.
Closes https://github.com/cds-snc/design-gc-conception/issues/1471
> feat: Change placement of copy button for template code examples

- .eleventy.js
Fix rendering of `requiredOn` shortcode to prevent failure when running accessibility tests. The returned list would leave some whitespace that 11ty would convert to `p` tags which would cause a list formatting error in the a11y test.
Using the code below
```
{% requiredOn locale true %}
{% endrequiredOn %}
```
1. On main branch, place the code example on a page.
2. Run the a11y tests.
3. Notice a list structure error after the page has been tested.
4. Switch to this branch and run the test again.
5. Notice no errors for the page.
> fix: requiredOn shortcode list formatting

- src/en/components/breadcrumbs/design.md
- src/en/components/date-modified/design.md
- src/en/components/language-toggle/design.md
- src/en/components/search/design.md
- src/en/components/signature/design.md
- src/fr/composants/bascule-de-langue/design.md
- src/fr/composants/chemin-de-navigation/design.md
- src/fr/composants/date-de-modification/design.md
- src/fr/composants/recherche/design.md
- src/fr/composants/signature/design.md
There was a minor miscommunication during the content updates for the new Canada.ca requirements guidance on the mandatory elements design pages. The subsections beginning with `What's required on [Canada.ca](http://canada.ca/)...` and `What's optional to include o [Canada.ca](http://canada.ca/)...` were intended to be added within `gcds-details` components. While this was noted in the ticket, it wasn't reflected in the content document, which led to the oversight.
This PR moves the new guidance sections, starting with `What's required on [Canada.ca](http://canada.ca/)...` and `What's optional to include o [Canada.ca](http://canada.ca/)...` into the appropriate `gcds-details` components.
- [EN preview](https://pr-569.djtlis5vpn8jd.amplifyapp.com/)
- [FR …
> fix: move new canada.ca requirments guidance into gcds-details components

- src/en/components/icon/use-case.md
- src/fr/composants/icone/cas-dutilisation.md
Fix icon use case display by reducing the icon preview box and displaying the chevron icons in a grid.
> fix: improve icon use case display

- .eleventy.js
- src/_includes/layouts/base.njk
- src/_includes/layouts/home.njk
- src/en/en.json
- src/en/get-involved.md
- src/fr/fr.json
- src/fr/simpliquer.md
- src/scripts/general.js
This PR updates the anchor on the "Subscribe to Mailing List" link (within the card) on the Get Involved page.
Previously, the link navigated to the top of the Contact Us page. It now correctly navigates the user to the "Get in contact with the design system team" section (H2) within that page.
This is the [issue ticket](https://github.com/cds-snc/gcds-docs/issues/560) for this change.
> feat: update "subscribe to mailing list" link anchor on get-involved page

- src/en/get-involved.md
- src/fr/simpliquer.md
Update Get Involved page content with the following changes:
- Remove `Tags` from `next priorities`.
- Remove `header`, `footer,` and `button` under `What else is coming soon` section as the work has been completed.
- [EN Get Involved page](https://pr-584.djtlis5vpn8jd.amplifyapp.com/en/get-involved/)
- [FR Get Involved page](https://pr-584.d35vdwuoev573o.amplifyapp.com/fr/simpliquer/)
This is the [issue ticket](https://github.com/cds-snc/gcds-docs/issues/578) for the change.
> feat: update get involved content

- src/_data/componenttags.js
- src/en/components/grid/use-case.md
- src/en/components/screenreader-only/use-case.md
- src/fr/composants/grille/cas-dutilisation.md
We decided to remove the `experimental` flag from the components page as it no longer serves the purpose we initially intended for it.
The `experimental` flag was removed from the `grid` and `screenreader only` components.
- Preview for [EN components page](https://pr-594.djtlis5vpn8jd.amplifyapp.com/en/components/)
- Preview for [FR components page](https://pr-594.d35vdwuoev573o.amplifyapp.com/fr/composants/)
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1690) for the change.
> feat: remove experimental tag from components page

- src/en/components/checkboxes/preview.md
- src/fr/composants/cases-a-cocher/preview.md
As mentioned in https://github.com/cds-snc/gcds-docs/issues/601, the checkboxes preview was not working correctly when clicking the checkboxes. This should fix the issue by correctly configuring the `gcds-checkboxes` in the preview files.
Closes https://github.com/cds-snc/gcds-docs/issues/601
> fix: checkboxes preview

- src/en/unsubscribe/unsubscribe.md
- src/fr/se-desabonner/se-desabonner.md
On the new unsubscribe page, even though the `translationKey` is set, it doesn't show the language toggle at the top. This PR fixes that.
Go to the unsubscribe page: https://design-system.alpha.canada.ca/en/unsubscribe/ to see the current/old version
Go to the preview page of this PR: https://pr-608.djtlis5vpn8jd.amplifyapp.com/en/unsubscribe
Go to the french version: https://pr-608.d35vdwuoev573o.amplifyapp.com/fr/se-desabonner
The language toggle should appear at the top
> chore: add translation toggle

- src/en/accessibility/accessibility.md
- src/en/components/breadcrumbs/design.md
- src/en/components/date-modified/design.md
- src/en/components/details/preview.md
- src/en/components/footer/design.md
- src/en/components/header/design.md
- src/en/components/language-toggle/design.md
- src/en/components/search/design.md
- src/en/components/signature/design.md
- src/fr/accessibilite/accessibilite.md
- src/fr/composants/bascule-de-langue/design.md
- src/fr/composants/chemin-de-navigation/design.md
- src/fr/composants/date-de-modification/design.md
- src/fr/composants/details/preview.md
- src/fr/composants/en-tete/design.md
- src/fr/composants/pied-de-page/design.md
- src/fr/composants/recherche/design.md
- src/fr/composants/signature/design.md
Small cleanup PR: When we added the new details section to all mandatory components, a minor bug in the details component required us to wrap content in extra `div` elements for proper rendering. That bug has since been resolved, so this PR removes the now-unnecessary `div` wrappers.
> fix: remove extra div in gcds-details component on mandatory pages

- src/en/css-shortcuts/position.md
- src/fr/raccourcis-css/position.md
Simplifying the CSS Shortcut position examples for now, to not have them block the launch. We can update them after we had time to work on the extra content needed for it.
> fix: update position examples

- src/en/css-shortcuts/css-shortcuts.md
- src/fr/demarrer/html.md
- src/fr/raccourcis-css/raccourcis-css.md
Updating two broken links to use the new link locations and optimizing the content that directs users to the installation page from the CSS Shortcuts landing page.
- [EN preview](https://pr-670.djtlis5vpn8jd.amplifyapp.com/en/css-shortcuts/)
- [FR preview](https://pr-670.d35vdwuoev573o.amplifyapp.com/fr/raccourcis-css/)
> fix: update two broken links + optimize shortcuts setup instructions

- src/en/pages/index.md
- src/fr/pages/index.md
As mentioned in https://github.com/cds-snc/design-gc-conception/issues/1924, the accessibility testing link on the home page was pointing to the wrong accessibility page. Correct the link to point to the right page.
> fix: Home page accessibility link
