src/_includes/layouts/base.njk, src/_includes/partials/breadcrumbs.njk, src/_includes/partials/header.njk, src/_includes/partials/nav.njk, src/index.md, src/styles/style.css
Temporary styling for the footer of the documentation page as well as very basic styling for the landing page.
Note: This styling is temporary and will be adjusted in the future.
=> feat: styling header + basic landing page

src/en/components/components.md, src/en/components/forms/form-guidance/form-guidance.md, src/en/components/forms/forms.md, src/en/foundations/typography/typography.md, src/fr/bases/typographie/typographie.md, src/fr/composants/elements-dinterface/bouton/bouton.md, src/fr/composants/elements-dinterface/elements-dinterface.md, src/fr/composants/formulaires/aide-a-la-conception-de-formulaires/aide-a-la-conception-de-formulaires.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/formulaires.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md, src/fr/contactez/contactez.md, src/fr/contactez/merci.md, src/fr/pages/index.md, utils/slugify.js
Make changes to content based on additional review. Changed `slugify` function to accommodate more complex headers.
=> Content changes based on review

src/en/components/forms/error-message/error-message.md, src/en/components/forms/form-guidance/form-guidance.md, src/en/components/forms/input/input.md, src/en/components/forms/textarea/textarea.md, src/en/components/interface-elements/button/button.md, src/fr/composants/elements-dinterface/bouton/bouton.md, src/fr/composants/formulaires/aide-a-la-conception-de-formulaires/aide-a-la-conception-de-formulaires.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/message-derreur/message-derreur.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md, src/styles/style.css
Update component examples based on this [figma file](https://www.figma.com/file/TAabTay6QTEVmDL56ErTtO/DS-Documentation-website-(core)?node-id=2%3A5) by using more component properties and adding a backdrop to the components.
=> Update component pages with better examples

.eleventy.js, src/_includes/partials/experimentalbanner.njk, src/styles/style.css
Integrate tokens into the documentation site.
=> integrate tokens

package.json, src/_includes/layouts/admin.njk, src/_includes/layouts/base.njk, src/_includes/layouts/home.njk, src/en/components/forms/error-message/error-message.md, src/en/components/forms/input/input.md, src/en/components/forms/textarea/textarea.md, src/en/components/interface-elements/button/button.md, src/en/installation.md, src/fr/composants/elements-dinterface/bouton/bouton.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/message-derreur/message-derreur.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md, src/fr/installation.md, src/styles/style.css
- move view code buttons right below the component example
- add type=module and nomodule scripts to templates
- update installation instructions
=> Update installation instructions

src/en/components/forms/input/input.md, src/en/components/forms/textarea/textarea.md, src/en/components/interface-elements/button/button.md, src/fr/composants/elements-dinterface/bouton/bouton.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md
Added figma page links to Button, Input and Textarea pages
=> add figma page links

package.json, src/_includes/layouts/home.njk, src/en/components/forms/error-message/error-message.md, src/en/components/forms/form-guidance/form-guidance.md, src/en/components/forms/input/input.md, src/en/components/forms/textarea/textarea.md, src/en/components/interface-elements/button/button.md, src/en/contact/contact.md, src/en/foundations/foundations.md, src/en/foundations/typography/typography.md, src/en/installation.md, src/en/pages/index.md, src/fr/bases/bases.md, src/fr/bases/typographie/typographie.md, src/fr/composants/elements-dinterface/bouton/bouton.md, src/fr/composants/formulaires/aide-a-la-conception-de-formulaires/aide-a-la-conception-de-formulaires.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/message-derreur/message-derreur.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md, src/fr/contactez/contactez.md, src/fr/installation.md, src/fr/pages/index.md, src/styles/style.css, src/variables/_variables.scss, src/variables/variables.css
=> Quick clean up existing documentation site

package.json, src/en/components/forms/fieldset/fieldset.md, src/en/components/forms/file-uploader/file-uploader.md, src/en/components/forms/select/select.md, src/en/components/interface-elements/banner/banner.md, src/en/components/interface-elements/footer/footer.md, src/en/components/interface-elements/grid/grid.md, src/en/components/interface-elements/header/header.md, src/en/components/interface-elements/site-menu/site-menu.md, src/en/components/interface-elements/verify-banner/verify-banner.md, src/fr/composants/elements-dinterface/banniere-de-verification/banniere-de-verification.md, src/fr/composants/elements-dinterface/banniere/banniere.md, src/fr/composants/elements-dinterface/grille/grille.md, src/fr/composants/elements-dinterface/navigation-intrapage/navigation-intrapage.md, src/fr/composants/elements-dinterface/pled-de-page/pled-de-page.md, src/fr/composants/formulaires/aide-a-la-conception-de-formulaires/aide-a-la-conception-de-formulaires.md, src/fr/composants/formulaires/champ-de-saisie/champ-de-saisie.md, src/fr/composants/formulaires/jeu-de-champs/jeu-de-champs.md, src/fr/composants/formulaires/menu-de-selection-deroulant/menu-de-selection-deroulant.md, src/fr/composants/formulaires/telechargeur-de-fichiers/telechargeur-de-fichiers.md, src/fr/composants/formulaires/zone-de-texte/zone-de-texte.md
Add new coming soon components for components that are developed but waiting on documentation.
=> add new coming soon components

src/_includes/layouts/base.njk, src/_includes/layouts/home.njk, src/en/installation.md, src/fr/installation.md
- add font awesome to docs site
- add font awesome link to installation instructions
=> add font awesome for icon support

src/en/foundations/typography/typography.md, src/fr/bases/typographie/typographie.md
Rename paragraph token to text to represent all text and not just paragraphs.
=> rename paragraph token to text

netlify/functions/submission-created.js, package.json
`node-fetch` was causing an error that would prevent contact form submission created function from running. Replaced it with `axios`.
=> Fix Netlify function

CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
Add guideline files:
SECURITY.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
=> add guideline files

src/_includes/layouts/base.njk, src/styles/style.css
Added temporary link to utility framework to work with until we publish the utility package.
=> add utility framework to docs

.eleventy.js, src/_includes/layouts/installation.njk, src/_includes/partials/installation/step-2-angular.njk, src/_includes/partials/installation/step-2-cdn.njk, src/_includes/partials/installation/step-2-choose.njk, src/_includes/partials/installation/step-2-figma.njk, src/_includes/partials/installation/step-2-node.njk, src/_includes/partials/installation/step-2-none.njk, src/_includes/partials/installation/step-2-react.njk, src/_includes/partials/installation/step-2-vue.njk, src/en/installation.md
Current content and styling for the installation page.
=> add styling and content for installation page

src/_data/nav.js, src/_includes/layouts/demo.njk, src/en/demo.md, src/en/foundations/colour/usage.md
- change nav to gc design system
- add external links to colour page
- add demo page
=> Minor page updates

.eleventy.js, package.json, src/_includes/layouts/base.njk, src/_includes/layouts/home.njk
Add new release version of components and utility package.
Feel free to merge if approved.
=> Add v1 version of packages

src/_includes/layouts/demo.njk, src/_includes/partials/helpus.njk, src/_includes/partials/installation/step-2-figma.njk, src/en/contact/contact.md, src/en/foundations/colour/usage.md, src/en/pages/index.md, src/fr/contactez/contactez.md, src/fr/demo.md, src/fr/pages/index.md
The gcds-icon component is not displaying correctly, for the sake of releasing, I temporarily replaced them with plain Font Awesome icons.
=> temporary fix for not working gcds-icon

README.md, package.json, src/_data/demo.js, src/_includes/layouts/demo.njk
- update readme with new EN content
- update demo with correct links + UF border class
=> Docs updates before release

src/_includes/layouts/component-documentation.njk, src/_includes/layouts/token-documentation.njk
=> fix page titles

src/_includes/partials/card-list.njk, src/en/components/breadcrumbs/use-case.md, src/en/components/lang-toggle/use-case.md, src/fr/composants/Chemin-de-navigation/case-dusage.md, src/fr/composants/bascule-de-la-langue/case-dusage.md, src/fr/composants/date-de-modification/case-dusage.md, src/fr/composants/en-tete/case-dusage.md, src/fr/composants/grille/case-dusage.md, src/fr/composants/message-derreur/base.md, src/fr/composants/message-derreur/case-dusage.md, src/fr/composants/pied-de-page/case-dusage.md, src/fr/composants/signature/case-dusage.md
- move tags below component images
- update status of components
- add french translation for tag
=> tags updates

src/_includes/partials/installation/step-2-cdn.njk
Fixed the CDN installation instructions that weren't updated with the new links yet.
=> update cdn installation instructions

src/_data/errormessage.js, src/en/components/details/code.md, src/en/components/fieldset/code.md, src/en/components/fieldset/design.md, src/en/components/fieldset/use-case.md, src/en/components/footer/code.md, src/en/components/header/code.md, src/en/components/header/design.md, src/en/components/input/code.md, src/en/components/input/design.md, src/en/components/input/use-case.md, src/en/components/radio/code.md, src/en/components/radio/design.md, src/en/components/stepper/code.md, src/en/components/textarea/code.md, src/en/components/textarea/design.md, src/styles/_typography.scss, src/styles/style.css
- add component links
- add code tags for attributes
=> add component links + add code tags for attributes

src/_data/installation.js, src/_includes/layouts/base.njk, src/_includes/layouts/home.njk, src/en/components/checkbox/code.md, src/fr/contactez/contactez.md
Small updates to site content
- Set footer `sub-links` to only two links
- Add spacing between paragraphs on French Contact page
- Add additional section to checkbox code page
- Add french default value to installation page
=> Small updates to site

README.md, package.json
Update readme with new doc site url
=> Update readme with new url

src/_includes/layouts/base.njk, src/_includes/layouts/home.njk
Update footer to load all mandatory links in the footer links band.
=> update footer to load all mandatory links

src/_includes/layouts/base.njk, src/_includes/layouts/home.njk
Add Google Analytics to `head` element and remove the `noindex` to allow indexing.
=> Add Google analytics and remove "noindex"

package.json, src/en/components/footer/use-case.md, src/en/components/header/use-case.md, src/en/pages/index.md, src/fr/composants/en-tete/case-dusage.md, src/fr/composants/pied-de-page/case-dusage.md, src/fr/pages/index.md, src/styles/_general.scss, src/styles/_typography.scss, src/styles/components/_tabs.scss, src/styles/style.css
- Add site-menu link to related components sections
- Fix mobile iframe display
- Fix link to not display as full width
- Adjust with new colour tokens
- Improve code for better multi-language support
- Update version, token + utility packages
=> Various updates

package.json, src/_data/nav.js, src/_includes/partials/nav.njk, src/styles/components/_tabs.scss, src/styles/style.css
Update gcds packages and replace `gcds-site-menu` with `gcds-top-nav`.
Fix accessibility error pointed out in #162.
Closes #162
=> Update components + small a11y fix

src/fr/composants/barre-de-navigation-laterale/base.md, src/fr/composants/barre-de-navigation-laterale/case-dusage.md
Add missing content for side-nav overview
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/484)
=> add missing content for side-nav overview

src/en/pages/index.md, src/fr/pages/index.md
Update featured component section on home page to use top-nav component.
=> Update featured component to use top-nav component

README.md
Updates the readme with the URL where the pages are accessible
=> Add URL paths to README

src/en/components/card/use-case.md, src/fr/composants/carte/case-dusage.md
Added missing alt description for card component preview images.
=> add alt text for card component preview image

src/en/components/side-navigation/design.md
Remove random extra character from `gcds-side-nav` design documentation.
=> Remove extra character

src/_data/installation.js, src/_includes/partials/installation/step-2-cdn.njk, src/_includes/partials/installation/step-2-node.njk, src/en/en.json, src/fr/fr.json
improve font awesome installation instructions + update font awesome link.
=> improve font awesome installation instructions

api/src/index.js
Small change to logging and response status code for spam prevention.
_fyi the two amplify previews are because I have another amplify app to test our terraform on my scratch account (to mimic production). please ignore it for now_
=> fix: change http response status code

src/en/components/button/base.md, src/en/components/card/base.md, src/en/components/details/base.md, src/en/components/fieldset/base.md, src/en/components/footer/base.md, src/en/components/grid/base.md, src/en/components/stepper/base.md, src/fr/composants/bouton/base.md, src/fr/composants/carte/base.md, src/fr/composants/details/base.md, src/fr/composants/grille/base.md, src/fr/composants/indicateur-detape/base.md, src/fr/composants/jeu-de-champs/base.md, src/fr/composants/pied-de-page/base.md
Update broken github + figma links on component pages.
=> fix: update broken github + figma links on component pages

src/fr/composants/barre-de-navigation-laterale/design.md
- Changed English anatomy heading to French
- Updated definition and other names
=> Content fixes to side nav

src/en/components/button/base.md, src/en/components/button/use-case.md, src/fr/composants/bouton/base.md, src/fr/composants/bouton/case-dusage.md
Update the button labels for better differentiation.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/690)
=> fix: update button labels for better differentiation

api/src/index.js
Fix for:
- https://github.com/cds-snc/design-gc-conception/issues/768
Tested the function on my scratch account
- Deployed image
- Checked how it looks like on cloudwatch logs
- Tested honeypot
- returns 204 and does nothing. 
- On the contact form page, nothing will happen
- If using another method of invocation, e.g. another form, postman or curl etc it shows 204 (success but no additional content returned)
- Added and tested fails on getting ssm parameters
- Logs the error, but still redirects user successfully. This will alert us and we'll have a copy of what the user tried to submit
- Added a skip if `NODE_ENV=development` for dev/testing purposes
- Tested fails on notify
- Logs the error, but still redirects user successfully. This will alert us and we'll have a copy of what the …
=> refactor: better error logging for our contact us submission API

src/en/components/button/base.md, src/fr/composants/bouton/base.md
Updating the button description.
=> fix: Update button description

src/en/components/card/base.md, src/en/not-about-us.md, src/fr/composants/carte/base.md
=> fix: update card description

api/src/index.js
- Fixes https://github.com/cds-snc/design-gc-conception/issues/868
=> fix: check for required fields

customHttp.yml, src/_includes/layouts/installation.njk, src/_includes/partials/installation/step-1.njk
The installation page isn't showing me the steps to install once I choose a dropdown item
=> fix: added the name attribute on the install page dropdown

src/en/pages/index.md, src/fr/pages/index.md
Fix "Tell us what you think" on English home page and switch French page to use links data
=> fix: Fix tell us what you think link to link to correct page

src/_data/breadcrumbs.js, src/_includes/partials/breadcrumbs.njk
Apply requested updates from [#928](https://github.com/cds-snc/design-gc-conception/issues/928). Changing "Home" to "GC Design System" and adding the breadcrumbs to the home page.
=> feat: Update home text in breadcrumb and add breadcrumbs to home page

api/src/freshdesk.js, api/src/index.js, api/src/package.json
PR fo this issue: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/zh/34
Please read more info in the ticket 👆, TIA
=> fix: contact us form message

src/en/pages/index.md, src/fr/pages/index.md
> Updated intro message
> Added page templates section – new image to be added next week
=> Update landing page

src/_data/installation.js
Update the Figma option in the select element to "Take me to the Figma Design Library .: Dirigez-moi vers la bibliothèque de conception Figma"
=> fix: Update figma item text on installation page

package.json
Update @cdssnc/gcds-utility package to latest version to include fixes for the Safari link style issue.
=> chore: Update @cdssnc/gcds-utility package to latest version

src/en/pages/index.md, src/fr/pages/index.md, src/images/common/home/icon-template.svg
Change patterns icon to templates icon on the homepage.
=> feat: Add new templates icon to homepage

src/en/get-involved.md, src/fr/simpliquer.md
Add new coming soon + contribute content + design to remove dependency on the card component.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1048)
=> refactor: update content for coming soon + contribute section

package.json
Very small PR to update the tokens + components package to the latest versions.
=> chore: update tokens + component package

package.json
Update the tokens and component packages to latest patch versions.
=> chore: Update GCDS packages to latest version

package.json
Update GCDS package dependencies
=> deps: update dependency versions for gcds

examples/component-name/base.md, examples/component-name/design.md, examples/component-name/use-case.md, scripts/gen-component-page.js
Found a few things to improve while creating the new pages for Date Input 😄
=> chore: update generate component page script

package.json
=> chore: update gcds-components and gcds-tokens

src/en/pages/index.md, src/fr/pages/index.md
Update featured component section on the website to show card and date input components.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1185)
=> refactor: update featured component on website

package.json
Update the component package to the newest version to address the [reported issue](https://github.com/cds-snc/gcds-components/issues/705) with breadcrumbs in Firefox.
=> chore: update components package

src/en/components/notice/code.md
Updated headings to sentence case.
---
---
> jouer au détective. Veuillez …
=> Notice component - Update code.md

src/fr/feuille-de-route.md
- Updated status of items
- Split Tag component and reduced scope of templates
- Added EN disclaimer, awaiting translation
---
---
> modification. Elles …
=> docs: update feuille-de-route.md

src/_data/registerdemos.js
Added Demo Days for:
Feb 18 English - 1-2pm
Feb 25 French - 1-2pm
---
---
> …
=> Update registerdemos.js - Add Feb dates

src/en/contact/contact.md, src/en/get-involved.md, src/fr/contactez/contactez.md, src/fr/simpliquer.md
Removing Get Involved page from Top Nav
Adding Contact Us to Top Nav
(added hideMain: true)
Removing Simpliquer from Top Nav
Adding Contactez to Top Nav
(Changed to hideMain: false, changed order to 3)
Ref to Zenhub Card [#1361](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1361)
---
---
> …
=> Update contact.md for top nav visibility

src/en/page-templates/topic.md, src/fr/modeles-de-page/topic.md
Hide the empty Topic template page from search .
=> fix: hide empty topic template page

src/en/get-involved.md, src/fr/simpliquer.md
Formatting changes and remove duplicate content
> remove duplicate content
> adjust styling 
> add/fix links
=> Fix: Update get-involved.md

package-lock.json, package.json
Update GC Design System components and tokens to latest versions including new smaller font size for header components and footer.
=> chore: Update GC Design Sytem packages to latest versions

package-lock.json, package.json
Update tokens, utility, and components packages to their latest versions.
=> chore: update tokens, utility, and components packages

src/en/get-involved.md, src/fr/simpliquer.md
---
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
=> Mailing list consistency

src/_data/registerdemos.js
Added June demo dates to Register for a Demo page
---
---
> jouer au …
=> Update registerdemos.js add june demo dates

src/_data/registerdemos.js
We needed to change the date for the upcoming French demo on June 24th as it fell on St. Jean Baptiste day (holiday in Quebec).  This was particularly sensitive as it is the French demo.   Date and time changed to Thursday June 26th at 3pm
---
> and/or any time-based elements that …
=> Update registerdemos.js to reflect date change

src/en/components/icon/base.md, src/fr/composants/icone/base.md
Making a few small content corrections for the icon component pages mentioned in [this issue](https://github.com/cds-snc/gcds-docs/issues/576).
=> fix: small content corrections to icon component pages

package-lock.json, package.json
Update `@cdssnc/gcds-components` and `@cdssnc/gcds-utility` to latest versions.
=> chore: Update GCDS packages

src/_data/registerdemos.js
Added demo registration info for upcoming demos running from October 2025 till April 2026
---
---
> modification. Elles aideront les développeurs à faire des …
=> Update registerdemos.js for dates till end of fiscal
